import React, { useState } from "react";
import RacingBarChart from "./RacingBarChart.js";
import useInterval from "./useInterval";
// import "./App.css";
import HorizontalTimelineComp from "./HorizontalTimeline";
import TimelineSlider from "../topicDetail2/timelineSlider";
const getRandomIndex = (array) => {
  return Math.floor(array.length * Math.random());
};

function TimeLine() {
  const [iteration, setIteration] = useState(0);
  const [start, setStart] = useState(false);
  const [eventDescription, setEventDescription] = useState("Hello");
  const mockData = {
    1228141435: {
      event: {
        description: "Brent Created Topic",
      },
      data: [
        {
          topic_id: 88,
          camp_id: 1,
          title: "Mind and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
          score: 0,
          level: 1,
        },
      ],
    },
    1228227835: {
      event: {
        description: "Michael added support",
      },
      data: [
        {
          topic_id: 88,
          camp_id: 1,
          title: "Mind and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
          score: 1,
          level: 1,
        },
      ],
    },
    1228314235: {
      event: {
        description: "Brent added support",
      },
      data: [
        {
          topic_id: 88,
          camp_id: 1,
          title: "Mind and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
          score: 2,
          level: 1,
        },
      ],
    },
    1228659835: {
      event: {
        description: "Robin Faichney added support",
      },
      data: [
        {
          topic_id: 88,
          camp_id: 1,
          title: "Mind and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
          score: 3,
          level: 1,
        },
      ],
    },
    1228746359: {
      event: {
        description: "Lenny added support",
      },
      data: [
        {
          topic_id: 88,
          camp_id: 1,
          title: "Mind and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
          score: 4,
          level: 1,
        },
      ],
    },
    1229178359: {
      event: {
        description: "Richwil added support",
      },
      data: [
        {
          topic_id: 88,
          camp_id: 1,
          title: "Mind and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
          score: 5,
          level: 1,
        },
      ],
    },
    1230870093: {
      event: {
        description: "Brent Created Topic Not Supernatural",
      },
      data: [
        {
          topic_id: 88,
          camp_id: 1,
          title: "Mind and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
          score: 6,
          level: 1,
        },
        {
          topic_id: 88,
          camp_id: 2,
          title: "Not Supernatural",
          review_title: "Approachable Via Science",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/2-Approachable-Via-Science#statement",
          score: 0,
          level: 2,
        },
      ],
    },
    1264738913: {
      event: {
        description: "New camps added",
      },
      data: [
        {
          topic_id: 88,
          camp_id: 1,
          title: "Mind and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
          score: 20,
          level: 1,
        },
        {
          topic_id: 88,
          camp_id: 2,
          title: "Approachable Via Science",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/2-Approachable-Via-Science#statement",
          score: 19,
          level: 2,
        },
        {
          topic_id: 88,
          camp_id: 6,
          title: "Representational and Real",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/6-Representational-Qualia#statement",
          score: 12,
          level: 3,
        },
        {
          topic_id: 88,
          camp_id: 17,
          title: "Mind-Brain Identity",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/17-Mind-Brain-Identity#statement",
          score: 8,
          level: 4,
        },
        {
          topic_id: 88,
          camp_id: 8,
          title: "Functional Equivalence",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/8-Functional-Prprty-Dualism#statement",
          score: 4.75,
          level: 5,
        },
        {
          topic_id: 88,
          camp_id: 9,
          title: "Comp Functionalism",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/9-Comp-Functionalism#statement",
          score: 1,
          level: 6,
        },
        {
          topic_id: 88,
          camp_id: 16,
          title: "quasi-functionalism",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/16-quasi-functionalism#statement",
          score: 1,
          level: 7,
        },
        {
          topic_id: 88,
          camp_id: 13,
          title: "UMSITW",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/13-D-L-S-create-UMSITW#statement",
          score: 1,
          level: 6,
        },
        {
          topic_id: 88,
          camp_id: 10,
          title: "Biological naturalism",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/10-Biological-naturalism#statement",
          score: 0.75,
          level: 6,
        },
        {
          topic_id: 88,
          camp_id: 7,
          title: "Phenomenal Properties",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/7-Qualia-are-Physical-Qualities#statement",
          score: 2,
          level: 5,
        },
        {
          topic_id: 88,
          camp_id: 15,
          title: "SCVR",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/15-SCVR#statement",
          score: 0.25,
          level: 5,
        },
        {
          topic_id: 88,
          camp_id: 14,
          title: "Higher-dimension Theories",
          review_title: "Smythies-Carr Hypothesis",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/14-Smythies-Carr-Hypothesis#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/14-Smythies-Carr-Hypothesis#statement",
          score: 1,
          level: 4,
        },
        {
          topic_id: 88,
          camp_id: 23,
          title: "representative/illusory",
          review_title: "representative/illusory",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/23-representative-illusory#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/23-representative-illusory#statement",
          score: 1,
          level: 3,
        },
        {
          topic_id: 88,
          camp_id: 24,
          title: "rep/Illusion/architecture",
          review_title: "rep/Illusion/architecture",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/24-rep-Illusion-architecture#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/24-rep-Illusion-architecture#statement",
          score: 1,
          level: 4,
        },
        {
          topic_id: 88,
          camp_id: 31,
          title: "Mind is brains illusion",
          review_title: "Mind is brains illusion",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/31-Mind-is-brains-illusion#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/31-Mind-is-brains-illusion#statement",
          score: 1,
          level: 5,
        },
        {
          topic_id: 88,
          camp_id: 32,
          title: "Bird/Mammal Limitation",
          review_title: "Bird/Mammal Limitation",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/32-Bird-Mammal-Limitation#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/32-Bird-Mammal-Limitation#statement",
          score: 1,
          level: 6,
        },
        {
          topic_id: 88,
          camp_id: 11,
          title: "Not a Genuine Problem",
          review_title: "Not a Genuine Problem",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/11-Not-a-Genuine-Problem#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/11-Not-a-Genuine-Problem#statement",
          score: 0,
          level: 3,
        },
        {
          topic_id: 88,
          camp_id: 12,
          title: "Subjective, Though Real",
          review_title: "Subjective, Though Real",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/12-Subjective--Though-Real#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/12-Subjective--Though-Real#statement",
          score: 0,
          level: 4,
        },
        {
          topic_id: 88,
          camp_id: 18,
          title: "Our exiestence is energy",
          review_title: "Qualia Emerge from Function",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/18-Qualia-Emerge-from-Function#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/18-Qualia-Emerge-from-Function#statement",
          score: 0,
          level: 3,
        },
        {
          topic_id: 88,
          camp_id: 30,
          title: "Perception",
          review_title: "Perception",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/30-Perception#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/30-Perception#statement",
          score: 0,
          level: 3,
        },
        {
          topic_id: 88,
          camp_id: 34,
          title: "panexperientialism",
          review_title: "Panexperientialism",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/34-Panexperientialism#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/34-Panexperientialism#statement",
          score: 0,
          level: 3,
        },
        {
          topic_id: 88,
          camp_id: 3,
          title: "Absolute space conscious",
          review_title: "Absolute space conscious",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/3-Absolute-space-conscious#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/3-Absolute-space-conscious#statement",
          score: 2,
          level: 2,
        },
        {
          topic_id: 88,
          camp_id: 4,
          title: "Consciousness fundamntal",
          review_title: "Consciousness fundamntal",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/4-Consciousness-fundamntal#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/4-Consciousness-fundamntal#statement",
          score: 1,
          level: 3,
        },
        {
          topic_id: 88,
          camp_id: 5,
          title: "Mind is a separate field",
          review_title: "Mind is a separate field",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/5-Mind-is-a-separate-field#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/5-Mind-is-a-separate-field#statement",
          score: 1,
          level: 4,
        },
        {
          topic_id: 88,
          camp_id: 20,
          title: "idenity of consciousness",
          review_title: "Orch OR",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/20-Orch-OR#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/20-Orch-OR#statement",
          score: 0,
          level: 5,
        },
        {
          topic_id: 88,
          camp_id: 22,
          title: "Spacetime geometry",
          review_title: "Spacetime geometry",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/22-Spacetime-geometry#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/22-Spacetime-geometry#statement",
          score: 0,
          level: 4,
        },
        {
          topic_id: 88,
          camp_id: 33,
          title: "Endogenous Light",
          review_title: "Nexus Theory",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/33-Nexus-Theory#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/33-Nexus-Theory#statement",
          score: 2,
          level: 2,
        },
        {
          topic_id: 88,
          camp_id: 25,
          title: "Advaita and Consciousness",
          review_title: "Advaita and Consciousness",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/25-Advaita-and-Consciousness#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/25-Advaita-and-Consciousness#statement",
          score: 1,
          level: 2,
        },
        {
          topic_id: 88,
          camp_id: 26,
          title: "Structurally coded",
          review_title: "Structurally coded",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/26-Structurally-coded#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/26-Structurally-coded#statement",
          score: 1,
          level: 2,
        },
        {
          topic_id: 88,
          camp_id: 27,
          title: "Coded Ordered Water",
          review_title: "Coded Ordered Water",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/27-Coded-Ordered-Water#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/27-Coded-Ordered-Water#statement",
          score: 1,
          level: 3,
        },
        {
          topic_id: 88,
          camp_id: 29,
          title: "5th dimensional qualia.",
          review_title: "5th dimensional qualia.",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/29-5th-dimensional-qualia-#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/29-5th-dimensional-qualia-#statement",
          score: 1,
          level: 2,
        },
        {
          topic_id: 88,
          camp_id: 19,
          title: "Loss of Consciousness",
          review_title: "Property Dualism",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/19-Property-Dualism#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/19-Property-Dualism#statement",
          score: 0,
          level: 2,
        },
        {
          topic_id: 88,
          camp_id: 28,
          title: "Not abstract mathematical",
          review_title: "Dualism",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/28-Dualism#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/28-Dualism#statement",
          score: 0,
          level: 2,
        },
        {
          topic_id: 88,
          camp_id: 35,
          title: "Invisible Homo sapiens",
          review_title: "Higher-dimension Theories",
          link: "https://canonizer.com/topic/88-Theories-of-Consciousness/35-Higher-dimension-Theories#statement",
          review_link:
            "https://canonizer.com/topic/88-Theories-of-Consciousness/35-Higher-dimension-Theories#statement",
          score: 0,
          level: 2,
        },
      ],
    },
    1885593600: {
      "event": {
          "description": "message here",
          "type": "add_camp",
          "id": 1,
          "nickname_id": 1,
          "topic_id": 2,
          "topic_name": "God",
          "algorithm_id": "blind_popularity",
          "namespace_id": 1,
          "review_namespace_id": 1,
          "topic_score": 48,
          "topic_full_score": 55,
          "as_of_date": 1885593600,
          "submitter_nick_id": 1,
          "created_by_nick_id": 1
      },
      "data": [
          {
              "topic_id": 2,
              "level": 1,
              "camp_id": 1,
              "title": "God",
              "review_title": "God",
              "link": "/topic/2-God/1",
              "review_link": "/topic/2-God/1",
              "score": 48,
              "full_score": 55,
              "submitter_nick_id": 1,
              "created_date": 1159293015,
              "is_valid_as_of_time": true,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": {
                  "1": {
                      "explicit": true
                  },
                  "786132": {
                      "explicit": true
                  }
              }
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 20,
              "title": "Mother Nature",
              "review_title": "Mother Nature",
              "link": "/topic/2-God/20-Mother-Nature#statement",
              "review_link": "/topic/2-God/20-Mother-Nature#statement",
              "score": 33.875,
              "full_score": 37,
              "submitter_nick_id": 1,
              "created_date": 1270001437,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 3,
              "camp_id": 3,
              "title": "Theist",
              "review_title": "Theist",
              "link": "/topic/2-God/3-Theist#statement",
              "review_link": "/topic/2-God/3-Theist#statement",
              "score": 13.875,
              "full_score": 15,
              "submitter_nick_id": 1,
              "created_date": 1270002627,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 4,
              "camp_id": 14,
              "title": "Monotheism",
              "review_title": "Monotheism",
              "link": "/topic/2-God/14-Monotheism#statement",
              "review_link": "/topic/2-God/14-Monotheism#statement",
              "score": 11.875,
              "full_score": 13,
              "submitter_nick_id": 1,
              "created_date": 1166282828,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 5,
              "camp_id": 6,
              "title": "Christian",
              "review_title": "Christian",
              "link": "/topic/2-God/6-Christian#statement",
              "review_link": "/topic/2-God/6-Christian#statement",
              "score": 5.25,
              "full_score": 6,
              "submitter_nick_id": 1,
              "created_date": 1166283154,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 6,
              "camp_id": 10,
              "title": "LDS",
              "review_title": "LDS",
              "link": "/topic/2-God/10-LDS#statement",
              "review_link": "/topic/2-God/10-LDS#statement",
              "score": 5,
              "full_score": 5,
              "submitter_nick_id": 1,
              "created_date": 1163364633,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 7,
              "camp_id": 11,
              "title": "Ex-Nihilo",
              "review_title": "Ex-Nihilo",
              "link": "/topic/2-God/11-Ex-Nihilo#statement",
              "review_link": "/topic/2-God/11-Ex-Nihilo#statement",
              "score": 2,
              "full_score": 2,
              "submitter_nick_id": 1,
              "created_date": 1163364724,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 7,
              "camp_id": 13,
              "title": "Transhumanist",
              "review_title": "Transhumanist",
              "link": "/topic/2-God/13-Transhumanist#statement",
              "review_link": "/topic/2-God/13-Transhumanist#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 1,
              "created_date": 1163364894,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 7,
              "camp_id": 12,
              "title": "Natural",
              "review_title": "Natural",
              "link": "/topic/2-God/12-Natural#statement",
              "review_link": "/topic/2-God/12-Natural#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 1,
              "created_date": 1163364809,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 6,
              "camp_id": 9,
              "title": "Catholic",
              "review_title": "Catholic",
              "link": "/topic/2-God/9-Catholic#statement",
              "review_link": "/topic/2-God/9-Catholic#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 1,
              "created_date": 1163364370,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 5,
              "camp_id": 19,
              "title": "God_Everywhere",
              "review_title": "God_Everywhere",
              "link": "/topic/2-God/19-God-Everywhere#statement",
              "review_link": "/topic/2-God/19-God-Everywhere#statement",
              "score": 4.625,
              "full_score": 5,
              "submitter_nick_id": 75,
              "created_date": 1216077294,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 6,
              "camp_id": 27,
              "title": "Endogenous Light Nexus",
              "review_title": "Endogenous Light Nexus",
              "link": "/topic/2-God/27-Endogenous-Light-Nexus#statement",
              "review_link": "/topic/2-God/27-Endogenous-Light-Nexus#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 159,
              "created_date": 1260101128,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 6,
              "camp_id": 22,
              "title": "Cells in the Body of God",
              "review_title": "Cells in the Body of God",
              "link": "/topic/2-God/22-Cells-in-the-Body-of-God#statement",
              "review_link": "/topic/2-God/22-Cells-in-the-Body-of-God#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 130,
              "created_date": 1245921486,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 5,
              "camp_id": 17,
              "title": "Neo-Canaanite",
              "review_title": "Neo-Canaanite",
              "link": "/topic/2-God/17-Neo-Canaanite#statement",
              "review_link": "/topic/2-God/17-Neo-Canaanite#statement",
              "score": 1,
              "full_score": 1,
              "submitter_nick_id": 46,
              "created_date": 1195845842,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 5,
              "camp_id": 7,
              "title": "Muslim",
              "review_title": "Muslim",
              "link": "/topic/2-God/7-Muslim#statement",
              "review_link": "/topic/2-God/7-Muslim#statement",
              "score": 1,
              "full_score": 1,
              "submitter_nick_id": 1,
              "created_date": 1167109133,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 5,
              "camp_id": 8,
              "title": "Jewish",
              "review_title": "Jewish",
              "link": "/topic/2-God/8-Jewish#statement",
              "review_link": "/topic/2-God/8-Jewish#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 1,
              "created_date": 1166283107,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 4,
              "camp_id": 15,
              "title": "Polytheism",
              "review_title": "Polytheism",
              "link": "/topic/2-God/15-Polytheism#statement",
              "review_link": "/topic/2-God/15-Polytheism#statement",
              "score": 2,
              "full_score": 2,
              "submitter_nick_id": 1,
              "created_date": 1166282912,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 5,
              "camp_id": 21,
              "title": "LDS",
              "review_title": "LDS",
              "link": "/topic/2-God/21-LDS#statement",
              "review_link": "/topic/2-God/21-LDS#statement",
              "score": 1,
              "full_score": 1,
              "submitter_nick_id": 1,
              "created_date": 1264905232,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 5,
              "camp_id": 16,
              "title": "Potential Godhood",
              "review_title": "Potential Godhood",
              "link": "/topic/2-God/16-Potential-Godhood#statement",
              "review_link": "/topic/2-God/16-Potential-Godhood#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 17,
              "created_date": 1182682960,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 4,
              "camp_id": 29,
              "title": "As a term with meaning",
              "review_title": "As a term with meaning",
              "link": "/topic/2-God/29-As-a-term-with-meaning#statement",
              "review_link": "/topic/2-God/29-As-a-term-with-meaning#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 286,
              "created_date": 1353894642,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 3,
              "camp_id": 4,
              "title": "Atheist",
              "review_title": "Atheist",
              "link": "/topic/2-God/4-Atheist#statement",
              "review_link": "/topic/2-God/4-Atheist#statement",
              "score": 12,
              "full_score": 13,
              "submitter_nick_id": 1,
              "created_date": 1287959814,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 4,
              "camp_id": 5,
              "title": "Atheist Hope",
              "review_title": "Atheist Hope",
              "link": "/topic/2-God/5-Atheist-Hope#statement",
              "review_link": "/topic/2-God/5-Atheist-Hope#statement",
              "score": 1,
              "full_score": 1,
              "submitter_nick_id": 1,
              "created_date": 1288146053,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 4,
              "camp_id": 35,
              "title": "Antitheist",
              "review_title": "Antitheist",
              "link": "/topic/2-God/35-Antitheist#statement",
              "review_link": "/topic/2-God/35-Antitheist#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 378,
              "created_date": 1552695231,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 3,
              "camp_id": 23,
              "title": "Pantheism",
              "review_title": "Pantheism",
              "link": "/topic/2-God/23-Pantheism#statement",
              "review_link": "/topic/2-God/23-Pantheism#statement",
              "score": 3.75,
              "full_score": 4,
              "submitter_nick_id": 1,
              "created_date": 1270002704,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 4,
              "camp_id": 24,
              "title": "Is God All Knowing?",
              "review_title": "Is God All Knowing?",
              "link": "/topic/2-God/24-Is-God-All-Knowing-#statement",
              "review_link": "/topic/2-God/24-Is-God-All-Knowing-#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 144,
              "created_date": 1249946625,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 3,
              "camp_id": 18,
              "title": "God is irrelevant",
              "review_title": "God is irrelevant",
              "link": "/topic/2-God/18-God-is-irrelevant#statement",
              "review_link": "/topic/2-God/18-God-is-irrelevant#statement",
              "score": 1.25,
              "full_score": 2,
              "submitter_nick_id": 1,
              "created_date": 1270002758,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 3,
              "camp_id": 25,
              "title": "agnostic",
              "review_title": "agnostic",
              "link": "/topic/2-God/25-agnostic#statement",
              "review_link": "/topic/2-God/25-agnostic#statement",
              "score": 1,
              "full_score": 1,
              "submitter_nick_id": 1,
              "created_date": 1270002802,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 2,
              "title": "Atheist",
              "review_title": "Atheist",
              "link": "/topic/2-God/2-Atheist#statement",
              "review_link": "/topic/2-God/2-Atheist#statement",
              "score": 9.75,
              "full_score": 10,
              "submitter_nick_id": 35,
              "created_date": 1354787777,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 3,
              "camp_id": 38,
              "title": "Big Bang Theory",
              "review_title": "Big Bang Theory",
              "link": "/topic/2-God/38-Big-Bang-Theory#statement",
              "review_link": "/topic/2-God/38-Big-Bang-Theory#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 520,
              "created_date": 1633524704,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 3,
              "camp_id": 26,
              "title": "Atheist Hope",
              "review_title": "Atheist Hope",
              "link": "/topic/2-God/26-Atheist-Hope#statement",
              "review_link": "/topic/2-God/26-Atheist-Hope#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 1,
              "created_date": 1288145791,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 37,
              "title": "Human Construct",
              "review_title": "Human Construct",
              "link": "/topic/2-God/37-Human-Construct#statement",
              "review_link": "/topic/2-God/37-Human-Construct#statement",
              "score": 1.125,
              "full_score": 2,
              "submitter_nick_id": 423,
              "created_date": 1629994583,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 36,
              "title": "God is not God are",
              "review_title": "God is not God are",
              "link": "/topic/2-God/36-God-is-not-God-are#statement",
              "review_link": "/topic/2-God/36-God-is-not-God-are#statement",
              "score": 1,
              "full_score": 1,
              "submitter_nick_id": 412,
              "created_date": 1611668981,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 39,
              "title": "Conscious Complex",
              "review_title": "Conscious Complex",
              "link": "/topic/2-God/39-Conscious-Complex#statement",
              "review_link": "/topic/2-God/39-Conscious-Complex#statement",
              "score": 0.625,
              "full_score": 1,
              "submitter_nick_id": 286,
              "created_date": 1634838792,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 28,
              "title": "Worshipped Being",
              "review_title": "Worshipped Being",
              "link": "/topic/2-God/28-Worshipped-Being#statement",
              "review_link": "/topic/2-God/28-Worshipped-Being#statement",
              "score": 0.5,
              "full_score": 2,
              "submitter_nick_id": 286,
              "created_date": 1353890781,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 3,
              "camp_id": 33,
              "title": "Outgrowing Worship - Good",
              "review_title": "Outgrowing Worship - Good",
              "link": "/topic/2-God/33-Outgrowing-Worship---Good#statement",
              "review_link": "/topic/2-God/33-Outgrowing-Worship---Good#statement",
              "score": 0.5,
              "full_score": 2,
              "submitter_nick_id": 286,
              "created_date": 1354739077,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 32,
              "title": "One's Ruling Logic",
              "review_title": "One's Ruling Logic",
              "link": "/topic/2-God/32-One-s-Ruling-Logic#statement",
              "review_link": "/topic/2-God/32-One-s-Ruling-Logic#statement",
              "score": 0.125,
              "full_score": 1,
              "submitter_nick_id": 286,
              "created_date": 1354178223,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 34,
              "title": "Posthuman Projection",
              "review_title": "Posthuman Projection",
              "link": "/topic/2-God/34-Posthuman-Projection#statement",
              "review_link": "/topic/2-God/34-Posthuman-Projection#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 67,
              "created_date": 1535084271,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 30,
              "title": "Recycle this",
              "review_title": "Recycle this",
              "link": "/topic/2-God/30-Recycle-this#statement",
              "review_link": "/topic/2-God/30-Recycle-this#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 286,
              "created_date": 1353895680,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          },
          {
              "topic_id": 2,
              "level": 2,
              "camp_id": 31,
              "title": "A metaphor",
              "review_title": "A metaphor",
              "link": "/topic/2-God/31-A-metaphor#statement",
              "review_link": "/topic/2-God/31-A-metaphor#statement",
              "score": 0,
              "full_score": 0,
              "submitter_nick_id": 286,
              "created_date": 1353895326,
              "is_disabled": 0,
              "is_one_level": 0,
              "subscribed_users": [],
              "parent_camp_is_disabled": 0,
              "parent_camp_is_one_level": 0
          }
      ]
  },
  };
  const events = Object.keys(mockData);
  const [data, setData] = useState(
    mockData[events[8]].data
    //   [
    //   {
    //     topic_id: 88,
    //     camp_id: 1,
    //     title: "Mind and Consciousness",
    //     link: "https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement",
    //     score: 0,
    //     level: 1,
    //   },
    // ]
  );

  let iterationCount = 0;

  useInterval(() => {
    if (start && events.length > iteration) {
    
      console.log(mockData[events[iteration]].data);

      setData(mockData[events[iteration]].data);
      setEventDescription(mockData[events[iteration]].event?.description);
      console.log(data);
      setIteration(iteration + 1);
      iterationCount++;
    }
  }, 1000);

  const handleEventSelection = (index) => {
    console.log(mockData[events[index]].data);

    setData(mockData[events[index]].data);
    setEventDescription(mockData[events[index]].event?.description);
    setIteration(index);
  };

  return (
    <React.Fragment>
      <h1 style={{ marginTop: "30px" }}>Racing Camps</h1>
      <TimelineSlider  setStart={setStart} start={start}/>
      <div style={{ overflow: "hidden" }}>
        <RacingBarChart data={data} />
      </div>
    </React.Fragment>
  );
}

export default TimeLine;
