// import "./globals.css";
import * as React from 'react';

import Layout from "src/hoc/layout/layoutApp";
import { Providers } from ".././store/provider";

import "antd/dist/antd.css";
import "react-quill/dist/quill.snow.css";

import "../../styles/globals.scss";
import "../../styles/variables.less";
import "../assets/fonticons/style.css";
import "../assets/scss/global.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Layout>
          {children}
          </Layout>
          </Providers>
      </body>
    </html>
  );
}
